name: Run meta pytest suite on repo

on:
  pull_request:
  push:

jobs:
  run-test:
    if: ${{ github.repository == 'ajparsons/poetry-auto-template' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install cookiecutter
        run: pip install -r requirements.dev.txt

      - name: run pytest
        run: python -m pytest